package com.example.plugins.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.trash.TrashHandler;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.model.TrashedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.trash.model.TrashEntry;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Libro service. Represents a row in the &quot;Libros&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.example.plugins.model.impl.LibroModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.example.plugins.model.impl.LibroImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Libro
 * @see com.example.plugins.model.impl.LibroImpl
 * @see com.example.plugins.model.impl.LibroModelImpl
 * @generated
 */
public interface LibroModel extends BaseModel<Libro>, GroupedModel, TrashedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a libro model instance should use the {@link Libro} interface instead.
     */

    /**
     * Returns the primary key of this libro.
     *
     * @return the primary key of this libro
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this libro.
     *
     * @param primaryKey the primary key of this libro
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the isbn of this libro.
     *
     * @return the isbn of this libro
     */
    public long getIsbn();

    /**
     * Sets the isbn of this libro.
     *
     * @param isbn the isbn of this libro
     */
    public void setIsbn(long isbn);

    /**
     * Returns the group ID of this libro.
     *
     * @return the group ID of this libro
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this libro.
     *
     * @param groupId the group ID of this libro
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this libro.
     *
     * @return the company ID of this libro
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this libro.
     *
     * @param companyId the company ID of this libro
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this libro.
     *
     * @return the user ID of this libro
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this libro.
     *
     * @param userId the user ID of this libro
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this libro.
     *
     * @return the user uuid of this libro
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this libro.
     *
     * @param userUuid the user uuid of this libro
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this libro.
     *
     * @return the user name of this libro
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this libro.
     *
     * @param userName the user name of this libro
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this libro.
     *
     * @return the create date of this libro
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this libro.
     *
     * @param createDate the create date of this libro
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this libro.
     *
     * @return the modified date of this libro
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this libro.
     *
     * @param modifiedDate the modified date of this libro
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the autor of this libro.
     *
     * @return the autor of this libro
     */
    @AutoEscape
    public String getAutor();

    /**
     * Sets the autor of this libro.
     *
     * @param autor the autor of this libro
     */
    public void setAutor(String autor);

    /**
     * Returns the titulo of this libro.
     *
     * @return the titulo of this libro
     */
    @AutoEscape
    public String getTitulo();

    /**
     * Sets the titulo of this libro.
     *
     * @param titulo the titulo of this libro
     */
    public void setTitulo(String titulo);

    /**
     * Returns the numero paginas of this libro.
     *
     * @return the numero paginas of this libro
     */
    public int getNumeroPaginas();

    /**
     * Sets the numero paginas of this libro.
     *
     * @param numeroPaginas the numero paginas of this libro
     */
    public void setNumeroPaginas(int numeroPaginas);

    /**
     * Returns the status of this libro.
     *
     * @return the status of this libro
     */
    @Override
    public int getStatus();

    /**
     * Returns the trash entry created when this libro was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this libro.
     *
     * @return the trash entry created when this libro was moved to the Recycle Bin
     * @throws SystemException if a system exception occurred
     */
    @Override
    public TrashEntry getTrashEntry() throws PortalException, SystemException;

    /**
     * Returns the class primary key of the trash entry for this libro.
     *
     * @return the class primary key of the trash entry for this libro
     */
    @Override
    public long getTrashEntryClassPK();

    /**
     * Returns the trash handler for this libro.
     *
     * @return the trash handler for this libro
     */
    @Override
    public TrashHandler getTrashHandler();

    /**
     * Returns <code>true</code> if this libro is in the Recycle Bin.
     *
     * @return <code>true</code> if this libro is in the Recycle Bin; <code>false</code> otherwise
     */
    @Override
    public boolean isInTrash();

    /**
     * Returns <code>true</code> if the parent of this libro is in the Recycle Bin.
     *
     * @return <code>true</code> if the parent of this libro is in the Recycle Bin; <code>false</code> otherwise
     * @throws SystemException if a system exception occurred
     */
    @Override
    public boolean isInTrashContainer();

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.example.plugins.model.Libro libro);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.example.plugins.model.Libro> toCacheModel();

    @Override
    public com.example.plugins.model.Libro toEscapedModel();

    @Override
    public com.example.plugins.model.Libro toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
