package com.meetic.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.meetic.model.UsuarioMeetic;
import com.meetic.model.UsuarioMeeticModel;
import com.meetic.model.UsuarioMeeticSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the UsuarioMeetic service. Represents a row in the &quot;MeeticServiceBuilder_UsuarioMeetic&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.meetic.model.UsuarioMeeticModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UsuarioMeeticImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UsuarioMeeticImpl
 * @see com.meetic.model.UsuarioMeetic
 * @see com.meetic.model.UsuarioMeeticModel
 * @generated
 */
@JSON(strict = true)
public class UsuarioMeeticModelImpl extends BaseModelImpl<UsuarioMeetic>
    implements UsuarioMeeticModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a usuario meetic model instance should use the {@link com.meetic.model.UsuarioMeetic} interface instead.
     */
    public static final String TABLE_NAME = "MeeticServiceBuilder_UsuarioMeetic";
    public static final Object[][] TABLE_COLUMNS = {
            { "userId", Types.BIGINT },
            { "groupId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "userName", Types.VARCHAR },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP },
            { "altura", Types.DOUBLE }
        };
    public static final String TABLE_SQL_CREATE = "create table MeeticServiceBuilder_UsuarioMeetic (userId LONG not null primary key,groupId LONG,companyId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,altura DOUBLE)";
    public static final String TABLE_SQL_DROP = "drop table MeeticServiceBuilder_UsuarioMeetic";
    public static final String ORDER_BY_JPQL = " ORDER BY usuarioMeetic.userId ASC";
    public static final String ORDER_BY_SQL = " ORDER BY MeeticServiceBuilder_UsuarioMeetic.userId ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.meetic.model.UsuarioMeetic"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.meetic.model.UsuarioMeetic"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.meetic.model.UsuarioMeetic"));
    private static ClassLoader _classLoader = UsuarioMeetic.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            UsuarioMeetic.class
        };
    private long _userId;
    private String _userUuid;
    private long _groupId;
    private long _companyId;
    private String _userName;
    private Date _createDate;
    private Date _modifiedDate;
    private double _altura;
    private UsuarioMeetic _escapedModel;

    public UsuarioMeeticModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static UsuarioMeetic toModel(UsuarioMeeticSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        UsuarioMeetic model = new UsuarioMeeticImpl();

        model.setUserId(soapModel.getUserId());
        model.setGroupId(soapModel.getGroupId());
        model.setCompanyId(soapModel.getCompanyId());
        model.setUserName(soapModel.getUserName());
        model.setCreateDate(soapModel.getCreateDate());
        model.setModifiedDate(soapModel.getModifiedDate());
        model.setAltura(soapModel.getAltura());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<UsuarioMeetic> toModels(UsuarioMeeticSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<UsuarioMeetic> models = new ArrayList<UsuarioMeetic>(soapModels.length);

        for (UsuarioMeeticSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _userId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setUserId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _userId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return UsuarioMeetic.class;
    }

    @Override
    public String getModelClassName() {
        return UsuarioMeetic.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("userId", getUserId());
        attributes.put("groupId", getGroupId());
        attributes.put("companyId", getCompanyId());
        attributes.put("userName", getUserName());
        attributes.put("createDate", getCreateDate());
        attributes.put("modifiedDate", getModifiedDate());
        attributes.put("altura", getAltura());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        Long groupId = (Long) attributes.get("groupId");

        if (groupId != null) {
            setGroupId(groupId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        String userName = (String) attributes.get("userName");

        if (userName != null) {
            setUserName(userName);
        }

        Date createDate = (Date) attributes.get("createDate");

        if (createDate != null) {
            setCreateDate(createDate);
        }

        Date modifiedDate = (Date) attributes.get("modifiedDate");

        if (modifiedDate != null) {
            setModifiedDate(modifiedDate);
        }

        Double altura = (Double) attributes.get("altura");

        if (altura != null) {
            setAltura(altura);
        }
    }

    @JSON
    @Override
    public long getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(long userId) {
        _userId = userId;
    }

    @Override
    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    @Override
    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @JSON
    @Override
    public long getGroupId() {
        return _groupId;
    }

    @Override
    public void setGroupId(long groupId) {
        _groupId = groupId;
    }

    @JSON
    @Override
    public long getCompanyId() {
        return _companyId;
    }

    @Override
    public void setCompanyId(long companyId) {
        _companyId = companyId;
    }

    @JSON
    @Override
    public String getUserName() {
        if (_userName == null) {
            return StringPool.BLANK;
        } else {
            return _userName;
        }
    }

    @Override
    public void setUserName(String userName) {
        _userName = userName;
    }

    @JSON
    @Override
    public Date getCreateDate() {
        return _createDate;
    }

    @Override
    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @JSON
    @Override
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    @Override
    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    @JSON
    @Override
    public double getAltura() {
        return _altura;
    }

    @Override
    public void setAltura(double altura) {
        _altura = altura;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            UsuarioMeetic.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public UsuarioMeetic toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (UsuarioMeetic) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        UsuarioMeeticImpl usuarioMeeticImpl = new UsuarioMeeticImpl();

        usuarioMeeticImpl.setUserId(getUserId());
        usuarioMeeticImpl.setGroupId(getGroupId());
        usuarioMeeticImpl.setCompanyId(getCompanyId());
        usuarioMeeticImpl.setUserName(getUserName());
        usuarioMeeticImpl.setCreateDate(getCreateDate());
        usuarioMeeticImpl.setModifiedDate(getModifiedDate());
        usuarioMeeticImpl.setAltura(getAltura());

        usuarioMeeticImpl.resetOriginalValues();

        return usuarioMeeticImpl;
    }

    @Override
    public int compareTo(UsuarioMeetic usuarioMeetic) {
        long primaryKey = usuarioMeetic.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof UsuarioMeetic)) {
            return false;
        }

        UsuarioMeetic usuarioMeetic = (UsuarioMeetic) obj;

        long primaryKey = usuarioMeetic.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<UsuarioMeetic> toCacheModel() {
        UsuarioMeeticCacheModel usuarioMeeticCacheModel = new UsuarioMeeticCacheModel();

        usuarioMeeticCacheModel.userId = getUserId();

        usuarioMeeticCacheModel.groupId = getGroupId();

        usuarioMeeticCacheModel.companyId = getCompanyId();

        usuarioMeeticCacheModel.userName = getUserName();

        String userName = usuarioMeeticCacheModel.userName;

        if ((userName != null) && (userName.length() == 0)) {
            usuarioMeeticCacheModel.userName = null;
        }

        Date createDate = getCreateDate();

        if (createDate != null) {
            usuarioMeeticCacheModel.createDate = createDate.getTime();
        } else {
            usuarioMeeticCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            usuarioMeeticCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            usuarioMeeticCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        usuarioMeeticCacheModel.altura = getAltura();

        return usuarioMeeticCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(15);

        sb.append("{userId=");
        sb.append(getUserId());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", userName=");
        sb.append(getUserName());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append(", altura=");
        sb.append(getAltura());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(25);

        sb.append("<model><model-name>");
        sb.append("com.meetic.model.UsuarioMeetic");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userName</column-name><column-value><![CDATA[");
        sb.append(getUserName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>altura</column-name><column-value><![CDATA[");
        sb.append(getAltura());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
