package com.example.plugins.model.impl;

import com.example.plugins.model.Libro;
import com.example.plugins.service.LibroLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Libro service. Represents a row in the &quot;Libros&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LibroImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LibroImpl
 * @see com.example.plugins.model.Libro
 * @generated
 */
public abstract class LibroBaseImpl extends LibroModelImpl implements Libro {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a libro model instance should use the {@link Libro} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            LibroLocalServiceUtil.addLibro(this);
        } else {
            LibroLocalServiceUtil.updateLibro(this);
        }
    }
}
